#pragma config(Sensor, S1,     0,              sensorSONAR)
#pragma config(Sensor, S2,     1,              sensorSONAR)
#pragma config(Sensor, S3,     2,              sensorSONAR)
#pragma config(Sensor, S4,     3,              sensorI2CHiTechnicAccel)
#pragma config(Motor,  motorA,          A,             tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorB,          E,             tmotorNXT, PIDControl, reversed, encoder)
#pragma config(Motor,  motorC,          D,             tmotorNXT, PIDControl, reversed, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#define ROBO NEGO_NEY

#define DEBUG_MOTORES false
#define DEBUG_EST_INICIAL false
#define DEBUG_MOV_INICIAL false

#define VEL_MAX 85
//#define kVelocidade 5.035 //94/56 distancia interna das rodas
#define DIST_MAX 22
#define DIST_MIN 18
#define VEL_MIN 60

#define DIAMETRO 56 //variavel que armazena o diametro da roda em mm que o robo usa
#define REDUCAO 1		//o valor passado para essa variavel indica que o robo tem uma reducao de 1 pra 1, ou seja, nao tem reducao
#define DIFERENCIAL true //variavel booleana que verifica se o robo tem ou nao diferencial
#define DIST_RODAS 12.8 //variavel que armazena a distancia em cm entre as rodas do robo

float AnguloSonares[3] = {45.0, -45.0, 0};

#include "../RinobotLib.h"

//#include "../movimentacao/3MotoresEscolha.h"
//#include "../estrategias/autonomas/AcelerometroDiferente.h"

int Estrategia[9] = {DISPLAY, NADA, CURVA, GIRA_GRAUS, OLEEE, OLEZINHO, ANDA_GIRA, RE_GIRA, DIAGONAL};

#include "initVariaveis.h"

task main()
{
	bool simular = false;	 //variavel booleana que define se os sensores serao simulados pelos botoes do NXT
	int valor_simulado[4]; //valores simulados dos sensores
	bool sensor_atualizou[4];

	bPlaySounds = true;
	UnmuteSound();
	nVolume = 1;
	//setBluetoothOn();
	//btConnect(1, "NXT");
	clearDebugStream();
	//flashLeft = nAvailFlash;
	InitVariaveis();
	ConfigurarMovimentacaoInicial(Estrategia);

	int Esperar = GerarMenu(ESPERAR_5_S, 2);


	movimentacaoInicial = GerarMenu(MOV_INICIAL, NUM_MOVES);
	movimentacaoInicial = Estrategia[movimentacaoInicial + 1];

	if(movimentacaoInicial == GIRA_GRAUS)
	{
		definirAngulo();
	}
	wait1Msec(200);

	//configurarEstrategiasAcelerometro();
	AcelerometroCair = GerarMenu(MENU_ACELEROMETRO, 2);

	escolherVisao();

	//EstrategiaSelecionada = GerarMenu(Estrategias, NumEstrategias);
	PressioneStart();

	//StartTask(Monitoramento);
	StartTask(AtualizarDisplay);
	StartTask(calcVelocidadeMotor);
	//StartTask(AtualizarSensores);
	//StartTask(SimularSensores);
	//StartTask(TratarSensores);
	//StartTask(Memoria);

	//StartTask(medirTempo);


	//EstrategiaEsperar = true;
	//iniciarEstrategiaInicial();

	//calcularFuncaoVelocidade();
	//MotorDireito = 0;
	//MotorEsquerdo = 0;
	//StartTask(calcVelocidadeMotor);
	velocidade(90, 0, 100, -100, &aVel, &bVel);
	ClearTimer(T1);
	ClearTimer(T2);
	ClearTimer(T4);
	int estado = ESPERANDO_5_SEG;
	int contou5segundos = 0;

	while(true)
	{
		AtualizarSensores(simular, valor_simulado, sensor_atualizou);
		if(TodosSensoresAtualizaram(sensor_atualizou)){
			ZerarFlagsSensor(sensor_atualizou);
			TratarSensores();
			switch(estado)
			{
			case ESPERANDO_5_SEG:
				contou5segundos = FuncaoEsperar(esperar);
				if(contou5segundos == true)
				{
					estado = EXECUTANDO_EST_INICIAL; //Se a FuncaoEsperar terminou de contar 5 segundos entao seu valor passa ser 1 e a maquina
					cair(170, 390);
				}
				//muda para o proximo estado
				break;

			case EXECUTANDO_EST_INICIAL:
				if(ExecutarEstrategiaInicial() == false){ //se a estrategia inicial encerrou
					estado = EXECUTANDO_EST_AUTO;
				}
				break;

			case EXECUTANDO_EST_AUTO: //aqui eh quando o robo esta executando a estrategia autonoma

				iniciarEstrategiaAutonoma();
				SelecionarTipoMovimentacao();
				//AtualizarDisplay();
				break;


			default: //caso aconteca alguma merda eu deixei isso aqui pro sensor sempre atualizar
				iniciarEstrategiaAutonoma();
				SelecionarTipoMovimentacao();
				//AtualizarDisplay();
				break;

			}
		}
	}
}
